### ISSUE TITLE
Pose Estimation 

### ISSUE THREAD

**Issue by williamhoole** [herohuyongtao/topotag#1]
How does topotag resolve pose ambiguity for coplanar markers ? And how is the accuracy influenced by pixel Oszillation (noise)?

**Comment by herohuyongtao** [comment]
TopoTag relies on the baseline node to resolve pose ambiguity, which defines the search starting position of the whole tag. You can check more details in the "3 TOPOTAG DESIGN" section in the paper ([arXiv link](https://arxiv.org/pdf/1908.01450.pdf)).

In terms of pixel noise, you can find more info in the "5.8 Noise Handing" section (and also "5.4 Localization Jitter and Accuracy
We" section) in the paper.
